### PR TITLE
Add support for DependencyCheck 5.3

### PR DESCRIPTION
**Pull request by TobiX**
Ran `mvn org.owasp:dependency-check-maven:5.3.0:aggregate -Dformats=ALL` against https://github.com/SonarSource/sonar-scanning-examples/tree/master/sonarqube-scanner-maven/maven-multimodule and put the output into the test directory (after pretty-printing with `jq` and `xmllint`).

After that it was just a bit of work to fix the tests :smile:

### CODE REVIEW

**Comment by TobiX** [comment]
Travis-CI fails because https://jira.sonarsource.com/browse/TRAVIS-19 (or even https://jira.sonarsource.com/browse/MMF-1371)

**Comment by Reamer** [comment]
Hi @TobiX,
noticed the parsing exception of missing md5 or sha1. Maybe a problem with [DependencyCheck](https://github.com/jeremylong/DependencyCheck).
Take a look into https://jeremylong.github.io/DependencyCheck/dependency-check.2.3.xsd.
md5 and sha1 should always be present.
```
<xs:element name="md5" type="xs:string" minOccurs="1" maxOccurs="1"/>
<xs:element name="sha1" type="xs:string" minOccurs="1" maxOccurs="1"/>
<xs:element name="sha256" type="xs:string" minOccurs="1" maxOccurs="1"/>
```

**Comment by TobiX** [comment]
Interesting. This only affects the JSON report. The offending part is:
```
      "isVirtual": true,
      "fileName": "org.sonarqube:module1:1.0-SNAPSHOT",
      "filePath": "/tmp/sonar-scanning-examples/sonarqube-scanner-maven/maven-multimodule/module1/pom.xml",
```
The same part in XML is:
```
    <dependency isVirtual="true">
      <fileName>org.sonarqube:module1:1.0-SNAPSHOT</fileName>
      <filePath>/tmp/sonar-scanning-examples/sonarqube-scanner-maven/maven-multimodule/module1/pom.xml</filePath>
      <md5/>
      <sha1/>
      <sha256/>
```
So, the elements are present, but empty.

**Comment by Reamer** [comment]
@TobiX I would prefer this small PR #230, to disable the requirement for md5 or sha1 values.
What are your thoughts?

**Pull request closed without merging**
