### PR TITLE
ignore 2 json fields to allow the plugin to work with dependency check 8.x

### LINKED ISSUE #748: Support dependency check 8.0.0
**Describe the bug**
When moving from 7.4.4 to 8.0.0, the plugin does not seem to be able to report the json or xml file

**To Reproduce**
After running the `check` task, then running `sonar:sonar -Dsonar.dependencyCheck.jsonReportPath=./target/dependency-check-report.json -Dsonar.dependencyCheck.htmlReportPath=./target/dependency-check-report.html`

**Current behavior**
It prints errors and does not import the issues into sonarqube. It does import the html file okay.
```
[INFO] Sensor Dependency-Check [dependencycheck]
[INFO] Process Dependency-Check report
[INFO] Using JSON-Reportparser
[WARNING] JSON-Analysis aborted
[INFO] Using XML-Reportparser
[INFO] Dependency-Check XML report does not exists. Please check property sonar.dependencyCheck.xmlReportPath:/local-working-dir/MYPROJECT-SITE-JOB1/${WORKSPACE}/dependency-check-report.xml
[INFO] XML-Analysis skipped/aborted due to missing report file
[INFO] Upload Dependency-Check HTML-Report
[INFO] Process Dependency-Check report (done) | time=391ms
[INFO] Sensor Dependency-Check [dependencycheck] (done) | time=391ms
```

**Expected behavior**
Expect it same behaviour as 7.4.4 with importing the issues

**Screenshots**

**Versions (please complete the following information):**

-   dependency-check 8.0.0
-   sonarqube 8.9.10
-   dependency-check-sonar-plugin 3.0.1

**Additional context**
none

### PR DESCRIPTION
**Pull request by sellersj**
Fixes #748 as a work around by ignoring a couple of new fields. Tested with ~250 java projects.

### CODE REVIEW

**Comment by Reamer** [comment]
I have looked at the new key "includedBy" and it seems perfect for Maven and Gradle projects. You can use the information to better add the issue to the project file.
Therefore I close this PR.

**Comment by sellersj** [comment]
My idea for the PR was just to get it working in the short term with the existing behavior. Do you have a timeline for a bigger change which would use this new field?

**Comment by Reamer** [comment]
As this is a small private project, I cannot give out a timeline.
Anyone who runs into error #748 now knows a way to stop the error from occurring. The only disadvantage is that everyone has to build the plugin themselves. I will not release this version, but rather work on the bigger changes.

**Comment by sellersj** [comment]
Okay. Thanks for your work!

**Pull request closed without merging**
