### PR TITLE
Add an additional rules for security hotspot

### LINKED ISSUE #249: Report findings as Security Hotspots (instead of violations)
**Is your feature request related to a problem? Please describe.**
OWASP dependency check will find vulnerabilities in dependencies which may not be a problem in practice (for example when the library is not used in a way that would make it vulnerable).

**Describe the solution you'd like**
I think all findings should be reported as security hotspots (https://docs.sonarqube.org/latest/user-guide/security-hotspots/) and then the developer can review the findings and confirm violations if this is the case.

**Describe alternatives you've considered**
There are no alternatives. The current implementation reports everything as violations directly causing annoying false positives.

### PR DESCRIPTION
**Pull request by Reamer**
Fixes #249

### CODE REVIEW

**Comment by Reamer** [comment]
@alixwar
Could you please test this feature and check, whether it meets your requirements. You must build a plugin version on your own.

**Comment by alixwar** [comment]
@Reamer I built the plugin locally and downloaded SonarQube 8.1 community edition but I was surprised to see that the Security Hotspots feature is not there. So it seems it is a commercial feature only?

To deploy a hand-hacked plugin into our licensed server environment is unfortunately not feasible.
But I can confirm that the violations were reported as violations (e.g. status quo) so I don't think there is any huge risk merging this and then I could quickly verify the release in our licensed server environment.

Perhaps someone from SonarSource could help us out here?

**Comment by Reamer** [comment]
Hi @alixwar,
Security-Hotspots are also available in the community edition. I've done some tests with the SonarQube 8.2 community edition. Can you please test with SonarQube 8.2?

You must also enable the function either via the global plug-in configuration or the sonar scanner configuration.

**Comment by alixwar** [comment]
@Reamer I've now installed SonarQube 8.2 and here I can actually see the Security Hotspots menu.
However, unfortunately all issues are reported as violations directly and not hotspots.
Have I missed something?

**Comment by Reamer** [comment]
Hi @alixwar 
You should see the following configuration option once you've built and installed the correct branch.
Security-Hotspot

As I wrote you can enable the function either via the global plug-in configuration or the sonar scanner configuration. Check out [this part of the official documentation.](https://docs.sonarqube.org/latest/analysis/analysis-parameters/)

**Comment by alixwar** [comment]
@Reamer I misunderstood you and had missed this option in my last verification. Will check now. Is there a reason to not have this option checked by default you think?

**Comment by Reamer** [comment]
I doesn't want release a new major version. A minor release step should not change the logic.

**Comment by alixwar** [comment]
@Reamer Unfortunately I end up in this state:

sechotspots

Unfortunately I can't find anything in the different server logs.

**Comment by Reamer** [comment]
My user interface looks good. I'm using Firefox. Which browser did you use? The user interface comes from SonarQube. This plugin does not affect the user interface.

Maybe you can test with another project. Take a look at our example folder.

**Comment by alixwar** [comment]
@Reamer I tried Chrome and also Edge. Will check with a different browser. I don't see how changing project would help. There is something wrong that needs to be fixed. If it helps I can find out exactly which rule violations are causing issues. Maybe it's a character or similar in the rule name that is the problem here

**Comment by alixwar** [comment]
Same problem with Firefox:

firefox1
firefox2

**Comment by Reamer** [comment]
> If it helps I can find out exactly which rule violations are causing issues.
This would be very helpful.

**Comment by alixwar** [comment]
@Reamer OK, I deleted the project in my local SonarQube instance and changed the setting to not use security hotspots and then reported again:

no-sec-hotspots

**Comment by Reamer** [comment]
@pethers Can you reproduce this issue?

**Comment by Reamer** [comment]
ping @pethers 
I would like to merge this change. I have no problems displaying the page with the security hotspots. Can you please test this feature with a small sample project?

**Comment by pethers** [comment]
@Reamer sorry for the delay, just noticed this now but will test it.

**Comment by pethers** [comment]
Tested it now and worked good, https://www.hack23.com/sonar/security_hotspots?id=com.hack23.cia%3Acia-all&sinceLeakPeriod=false

**Pull request merged**
