### PR TITLE
Parse exceptions

### PR DESCRIPTION
**Pull request by TobiX**
Try to parse analysis exceptions & show them in the SonarQube dashboard.

Screenshot:
grafik

### CODE REVIEW

**Comment by TobiX** [comment]
This contains the same test refactor as my other pull request - This seems a little bit more important because an analysis exception might randomly break this plugin otherwise...

**Comment by Reamer** [comment]
Can we split this PRs?

**Comment by TobiX** [comment]
> Can we split this PRs?

In what direction? Shall I split the test refactoring from the new feature? Or do you want me to split the exception parsing in some way?

**Comment by Reamer** [comment]
> > Can we split this PRs?
> 
> In what direction? Shall I split the test refactoring from the new feature? Or do you want me to split the exception parsing in some way?

Sorry, I switched to the wrong tab in my review process and thought that you mixed #229 and #228

**Comment by Reamer** [comment]
Closed because of #240

**Pull request closed without merging**
